dendrite: Bump to v0.8.3

diff --git a/kustomize/rwx/base/configmap.yaml b/kustomize/rwx/base/configmap.yaml
--- a/kustomize/rwx/base/configmap.yaml
+++ b/kustomize/rwx/base/configmap.yaml
@@ -16,18 +16,28 @@ data:
 
   backup_database.sh: |
     #!/usr/bin/env bash
+
     set -e
     set -x
-
-    apt update && apt install -y curl
-
-    curl -q -L "https://github.com/wal-g/wal-g/releases/download/v1.1/wal-g-pg-ubuntu-20.04-amd64.tar.gz" -o wal-g-pg.tar.gz
-    echo "c922c46c770fa5edd38bd60bfacdb92d813272d5d6bd2fc83ef57084b9c6c68c  wal-g-pg.tar.gz" | sha256sum -c
-    tar xvf wal-g-pg.tar.gz
-    install wal-g-pg-ubuntu-20.04-amd64 /usr/local/bin/wal-g
 
     export PGUSER=postgres
     export PGPASSWORD="${POSTGRES_PASSWORD}"
     export PGHOST=postgres
 
-    /usr/local/bin/wal-g backup-push "/var/lib/postgresql/data"
+    dt=$(date '+%d/%m/%Y %H:%M:%S');
+    fileDt=$(date '+%d_%m_%Y_%H_%M_%S');
+    backUpFileName="$KUBEGRES_RESOURCE_NAME-backup-$fileDt.gz"
+    backUpFilePath="$BACKUP_DESTINATION_FOLDER/$backUpFileName"
+
+    echo "$dt - Starting DB backup of Kubegres resource $KUBEGRES_RESOURCE_NAME into file: $backUpFilePath";
+    echo "$dt - Running: pg_dumpall -h $BACKUP_SOURCE_DB_HOST_NAME -U postgres -c | gzip > $backUpFilePath"
+
+    pg_dumpall -h $BACKUP_SOURCE_DB_HOST_NAME -U postgres -c | gzip > $backUpFilePath
+
+    if [ $? -ne 0 ]; then
+      rm $backUpFilePath
+      echo "Unable to execute a BackUp. Please check DB connection settings"
+      exit 1
+    fi
+
+    echo "$dt - DB backup completed for Kubegres resource $KUBEGRES_RESOURCE_NAME into file: $backUpFilePath";
